// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

namespace Steamworks
{
	/// In a few places we need to set configuration options on listen sockets and connections, and
	/// have them take effect *before* the listen socket or connection really starts doing anything.
	/// Creating the object and then setting the options "immediately" after creation doesn't work
	/// completely, because network packets could be received between the time the object is created and
	/// when the options are applied.  To set options at creation time in a reliable way, they must be
	/// passed to the creation function.  This structure is used to pass those options.
	///
	/// For the meaning of these fields, see ISteamNetworkingUtils::SetConfigValue.  Basically
	/// when the object is created, we just iterate over the list of options and call
	/// ISteamNetworkingUtils::SetConfigValueStruct, where the scope arguments are supplied by the
	/// object being created.
	[System.Serializable]
	[StructLayout(LayoutKind.Sequential)]
	public struct SteamNetworkingConfigValue_t
	{
		/// Which option is being set
		public ESteamNetworkingConfigValue m_eValue;

		/// Which field below did you fill in?
		public ESteamNetworkingConfigDataType m_eDataType;

		/// Option value
		public OptionValue m_val;

		// NativeAOT patch (Milton fork): the original used [StructLayout(LayoutKind.Explicit)]
		// with IntPtr fields overlapping value types at offset 0. ILC rejects overlapping a
		// pointer-shaped field with non-pointer value types ("because of field offset '0'").
		// We keep the identical 8-byte native ABI via a single blittable backing field and
		// expose the original members as properties, so callers are unchanged and AOT compiles.
		[StructLayout(LayoutKind.Sequential)]
		public struct OptionValue
		{
			private long m_storage;

			public int m_int32
			{
				get { return (int)m_storage; }
				set { m_storage = value; }
			}

			public long m_int64
			{
				get { return m_storage; }
				set { m_storage = value; }
			}

			public unsafe float m_float
			{
				get { int v = (int)m_storage; return *(float*)&v; }
				set { int v = *(int*)&value; m_storage = v; }
			}

			public IntPtr m_string // Points to your '\0'-terminated buffer
			{
				get { return (IntPtr)m_storage; }
				set { m_storage = (long)value; }
			}

			public IntPtr m_functionPtr
			{
				get { return (IntPtr)m_storage; }
				set { m_storage = (long)value; }
			}
		}
	}
}

#endif // !DISABLESTEAMWORKS